---
title: "CASO PRACTICO - ANALITICA ESPACIAL"
output: html_notebook
---

```{r}
# Preparamos el entorno, importamos librerias y leemos ficheros
rm(list=ls())
setwd("/home/chema/MasterBI/practicas/09_05.RSpatial/RSpatialTutorial/")
library(rgdal)
library(rgeos)
library(tmap)
library(OpenStreetMap)

# Configuramos graficos estaticos
tmap_mode("plot")

# Leemos datos
LondonCustomer <- read.csv('/home/chema/MasterBI/practicas/09_05.RSpatial/RSpatialTutorial/data/LondonCustomer.csv',header= T,sep = ';', na.strings = "?")
LondonSports <- readOGR(dsn='/home/chema/MasterBI/practicas/09_05.RSpatial/RSpatialTutorial/data', layer="london_sport")

```

# 1. Analitica para cierre de 3 oficinas.
## Criterio de seleccion: sucursales con menor volumen de negocio 
### de clientela menor de 55 años
### Volumen de negocio = suma de consumo de todos los productos

```{r}
# Previsualizamos los datos
head(LondonCustomer)
# Comprobamos la estructura del objeto
str(LondonSports)
```

```{r}
# Nos quedamos con los clientes menores de 55 años
LondonCustomerAnalisis <- LondonCustomer[LondonCustomer$AGE<55, ]
# Sumamos sus consumos
LondonCustomerAnalisis$NETPRICE_PRO14_AMT <- as.numeric(LondonCustomerAnalisis$NETPRICE_PRO14_AMT)
LondonCustomerAnalisis$Suma = rowSums(LondonCustomerAnalisis[ , 7:13])
# Nos quedamos con los 3 municipios de menor consumo:
VentasDistrito <- sort(tapply(LondonCustomerAnalisis$Suma, LondonCustomerAnalisis$name, sum), decreasing = F)
VentasDistritoPeores <- head(VentasDistrito, 3)
VentasDistritoPeores
print('Los distritos con peor venta en el rango de edad de menores de 55 años son:')
names(VentasDistritoPeores)
# Seleccionamos esos distritos con las menores ventas, para destacarlos en el mapa:
LondonSportsBajaVenta <- LondonSports$name == names(VentasDistritoPeores)[1] | LondonSports$name == names(VentasDistritoPeores)[2] | LondonSports$name == names(VentasDistritoPeores)[3]
LondonSportsCierre <- LondonSports[LondonSportsBajaVenta,]
plot(LondonSports, col = "lightgreen")
plot(LondonSportsCierre, col="red", add = TRUE)
```
# 2. Analisis de trasvase de clientes a otras oficinas, segun cercania por centro geografico de los distritos

```{r}
# Obtenemos los centroides de cada distrito y los visualizamos junto con los cerrados
cent_London <- gCentroid(LondonSports, byid = T)
plot(LondonSports)
plot(LondonSportsCierre, col="red", add = TRUE)
points(cent_London,pch=1)

# Zonas a menos de 1,4 km del centroide geografico de los cerrados. Lo guardamos en un buffer
centCierre <- cent_London[LondonSportsBajaVenta,]
zonas_buffer <- gBuffer(spgeom = centCierre, width = 1400)
# Visualizamos las sucursales a cerrar y aquellas que pueden sustituirlas por cercania
municipios_buffer = LondonSports[zonas_buffer, ]
plot(LondonSports, col = "lightgrey")
plot(municipios_buffer, col = "orange", add = TRUE)
plot(LondonSportsCierre, col="red", add = TRUE)
plot(centCierre, col="green", add = TRUE,pch=1)

```

```{r}
str(zonas_buffer)
```

