```{r}
# Lectura de ficheros sin conocer su estructura
datos<-read.csv(file="http://archive.ics.uci.edu/ml/machine-learning-databases/autos/imports-85.data", na.strings = "?", header = FALSE)
# 2. Haz un sumario del dataframe.
summary(datos)
```
```{r}
# 3. Qué dimensión tiene el dataframe?
dim(datos)
names(datos)[1]
```
```{r}
# 4. Inspecciona los datos, de qué clase es cada tipo? Extrae los distintos valores que toman los factores.
# install.packages("dplyr")
library(dplyr)
# print(distinct(datos,datos[,1]))
for (indice in 1:dim(datos)[2]) {
  print(c(names(datos)[indice], class(datos[,indice])))
  print(distinct(datos,datos[,indice]))
}
#datos$V1
#class(datos[,4])
```
```{r}
# 5. Indica la proporción de  valores faltantes por columna usando sum e is.na y un apply (usa nrow).
Cant <- nrow(datos)
# Contabilizamos la cantidad de elementos faltantes por columna:
NAs <- apply(is.na(datos),2,sum)
print(NAs)
print(Cant)
print (NAs/Cant*100)
```
```{r}
# 6. Edita la primera columna llevándola al rango 0-5.
datos$V1
datos$V1 <- datos$V1 + 2
datos$V1
```
```{r}
# 7. Da una media de los valores de la primera columna respecto a la columna de número de puertas del coche.
tapply(datos$V1, datos$V6, mean)
```
```{r}
# 8. Extrae los coches  audi que son cuatro puertas con valor V13 menor que 55
datos[(datos$V3=='audi')&(datos$V6=='four')&(datos$V13<55),]
```

